export const ROUTES = {
  welcome: "/welcome",
  login: "/login",
  home: "/",
  checkIn: "/check-in",
  scan: "/scan",
  inside: "/inside",
  history: "/history",
  approvals: "/approvals",
  preRegister: "/pre-register",
  analytics: "/analytics",
  pass: "/pass",
  myPass: "/my-pass",
  profile: "/profile",
  publicPass: "/pass/:token",
} as const;
